# -*- coding: utf-8 -*-
"""Despliegue-clasificacion-ataqueCardiaco.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ExGSh5JahEcdkL43PhQ2pNnNlhbewjUS

# Despliegue

- Cargamos el modelo
- Cargamos los datos futuros
- Preparar los datos futuros: normalizar, dummies
- Aplicamos el modelo para la predicción
"""

#Cargamos librerías principales

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

#Cargamos el modelo
import pickle
filename = 'modelo-cla.pkl'
modelo, labelencoder, variables, min_max_scaler = pickle.load(open(filename, 'rb'))

#modelo

#print(variables)

#print(modelo.classes_)

#print(labelencoder.classes_)

#Cargamos los datos futuros
#data = pd.read_excel("/content/ataque_corazon.xlsx")
#data.head()

#data['age'].describe()

#data['avg_glucose_level'].describe()

#data.info()

# Interfaz gráfica

import streamlit as st

# Diseño visual
st.markdown("""
<style>
    .titulo {
        background: linear-gradient(120deg, #164e63, #0f766e);
        padding: 25px;
        border-radius: 15px;
        color: white;
        text-align: center;
        margin-bottom: 25px;
    }

    .titulo h1 {
        color: white;
    }
</style>
""", unsafe_allow_html=True)

st.markdown("""
<div class="titulo">
    <h1>❤️ Predicción de un ataque cardíaco</h1>
    <p>Ingresa los datos para realizar la predicción.</p>
</div>
""", unsafe_allow_html=True)

st.subheader("Información de la persona")

# Distribución de los campos en dos columnas
col1, col2 = st.columns(2)

with col1:
    age = st.slider('age', min_value=1, max_value=82, value=20, step=1)
    avg_glucose_level = st.slider('avg_glucose_level', min_value=55, max_value=272, value=80, step=1)
    smoking_status = st.selectbox('smoking_status', ["'never smoked'", "'formerly smoked'","Unknown","smokes"])

with col2:
   hypertension = st.selectbox('hypertension', ['No', 'Yes'])
   ever_married = st.selectbox('ever_married', ['No', 'Yes'])
   heart_disease = st.selectbox('heart_disease', ['No', 'Yes'])

#Dataframe
datos = [[age,avg_glucose_level,smoking_status,hypertension,ever_married,heart_disease]]
data = pd.DataFrame(datos, columns=['age', 'avg_glucose_level','smoking_status','hypertension','ever_married','heart_disease']) #Dataframe con los mismos nombres de variables

#Se realiza la preparación de datos
data_preparada=data.copy()

#En despliegue drop_first= False
data_preparada = pd.get_dummies(data_preparada, columns=['smoking_status','hypertension','heart_disease','ever_married'], drop_first=False, dtype=int)
data_preparada.head()

#EN LOS DESPLIEGUES NUNCA BORRAMOS DUMMIES, OSEA DROP FIRST SIEMPRE SIEMPRE SERÁ FALSO

#Se adicionan las columnas faltantes
#Porque por dummies y otras cosas (varaibles sin registros) se perdieron algunas columnas so con reindex las llenamos asi sea a punta de cero
data_preparada=data_preparada.reindex(columns=variables,fill_value=0)
data_preparada.head()

#Se normaliza la edad para predecir con Knn, Red, SVM, Reg
#En los despliegues no se llama fit
data_preparada[['age','avg_glucose_level']]= min_max_scaler.transform(data_preparada[['age','avg_glucose_level']])
data_preparada.head()

"""# Predicciones"""

#Hacemos la predicción con el knn
Y_pred = modelo.predict(data_preparada)
print(Y_pred)

Y_pred = labelencoder.inverse_transform(Y_pred)

if Y_pred[0] == 'Yes':
    st.error("Predicción del modelo: Yes")
else:
    st.success("Predicción del modelo: No")

data['Prediccion']=Y_pred
data.head()

data

# Recordar medida de error del modelo

st.warning("El modelo tiene una evaluación compuesta por una exactitud del 87% y un f1 de 81.2%")